language: node_js
node_js:
  - "4.0"
before_install:
  - npm update -g npm
  - npm install -g bob coveralls --loglevel error
script:
  - cd feedpaper-api && make build
  - cd feedpaper-data && make build
  - cd feedpaper-web && make build
