language: node_js
node_js:
  - "6.3"
before_install:
  - npm update -g npm
  - npm install -g bob coveralls --loglevel error
  - wget https://releases.hashicorp.com/terraform/0.6.16/terraform_0.7.0_linux_amd64.zip
  - mkdir -p ~/opt/terraform/
  - unzip terraform_0.7.0_linux_amd64.zip -d ~/opt/terraform/
script:
  - export PATH=~/opt/terraform/:$PATH
  - export FEEDPAPER_ENV=ci
  - export FEEDPAPER_CFG=`pwd`/conf
  # - cd feedpaper-api && make build && cd ..
  # - cd feedpaper-data && make build && cd ..
  - cd feedpaper-web && bob dep && make build && cd ..
