sudo: false
language: node_js
node_js:
  - "6"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - npm update -g npm
  - npm install -g bob coveralls --loglevel error
  - wget https://releases.hashicorp.com/terraform/0.9.5/terraform_0.9.5_linux_amd64.zip
  - mkdir -p ~/opt/terraform/
  - unzip terraform_0.9.5_linux_amd64.zip -d ~/opt/terraform/
script:
  - export PATH=~/opt/terraform/:$PATH
  - export FEEDPAPER_ENV=ci
  - export FEEDPAPER_CFG=`pwd`/conf
  # - cd feedpaper-api && make build && cd ..
  # - cd feedpaper-data && make build && cd ..
  - cd feedpaper-web && bob dep && make build && cd ..
